version: "3.9"

services:
  system_monitor_bot:
    build:
      context: ../../bots/system_monitoring
      dockerfile: Dockerfile

    container_name: system_monitoring_bot

    restart: unless-stopped

    env_file:
      - .env

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
